apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: myimage
        image: demo2project.azurecr.io/myimage:v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myservice1
spec:
  type: LoadBalancer
  selector:
    app: myimage
  ports:
    - port: 80
      targetPort: 80